### ISSUE TITLE
Task: Create a UI design for the building controller

### ISSUE THREAD

**Issue by shreyas-newa** [Allen-ISD-Computer-Science/REPO_NASA_EnvironmentalControls_2024#38]

**Comment by rishibadal726** [comment]
> What is the progress on this task [@rishibadal726](https://github.com/rishibadal726)?

The progress on my task is close to finished as I have officially added the touch map feature(it has a dropdown feature, so when you click on the dropdown arrow a map will appear of the spaceship), and I will now be adding the voice control feature to the UI design for the Building Controller, which will enable voice activated commands. Also, this UI design for the building controller will be used as a part of the troubleshooting process for all the nodes in the network, plus testing if all nodes are alive and sending and receiving messages.

**Comment by Mukesh-Kalikaya** [comment]
When can we expect this to be completed? This was meant to be finished on Friday, Feb 16.
